version: '3.8'

services:

  jenkins:
    image: bah-jenkins
    container_name: jenkins
    env_file:
      - jenkins.env
    privileged: true
    user: root
    ports:
      - 80:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/local/bin/docker

  pypi:
    image: pypiserver/pypiserver:latest
    command: -P .htpasswd packages
    ports:
      - 8081:8080
    volumes:
      - .htpasswd:/data/.htpasswd


volumes:
  jenkins-data:
